config/routes.rb
Rails.application.routes.draw do
  # Active admin
  ActiveAdmin.routes(self)

  # API
  mount ApplicationAPI => '/api'

  # sidekiq
  require 'sidekiq/web'
  authenticate :user, lambda { |user| user.permission.superadmin? || user.permission.admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  root 'main#index'
  resources :coming_soon_requests, only: [:new, :create], path: '', path_names: {
    new: 'coming-soon',
    create: 'coming-soon'
  } do
    collection do
      post 'main-search', action: :main_search
      get 'coming-soon/thank-you', action: :success, as: :success
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'users/sign_in_as/:type', to: 'users/sessions#sign_in_as', as: :sign_in_as
  end
  resources :users, only: [:index, :destroy]
  resources :delocoins, only: [:new, :create]

  namespace :my do
    resources :welcome, only: :index
    resources :index, only: :index
    resource :user, only: [:edit, :update]
    resource :settings, only: [:edit, :update]
    resources :billing, only: [:index, :create] do
      member do
        get 'confirm', as: :confirm
        post 'confirm'
        get 'status', as: :status
      end
      collection do
        get 'history', as: :history
        resources :yandex_endpoint, path: 'yandex', only: [] do
          get 'success', on: :collection
          match 'fail', via: [:get, :post], on: :collection
        end
      end
    end
    resources :delocoin, only: [:index] do
      collection do
        get 'history', as: :history
      end
    end
    resources :portfolios, except: [:index, :destroy]
  end

  resources :profiles, only: [:show, :edit, :update], path: 'profile'
  resources :profiles, only: [:new, :create]

  resources :tasks, only: [:show, :edit, :update, :destroy], path: 'task' do
    resources :replies, only: [:show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create]
      member do
        get 'cancel_decline'
        get 'decline'
        get 'accept'
        get 'delete'
      end
    end
  end
  resources :tasks, only: [:new, :create], path_names: { new: 'new(/:category_id)' }

  scope '(/:city_code)' do
    resources :tasks, only: [:index] do
      collection do
        get '/my(/:category_id)',         action: :index, as: :my,        defaults: { scope: :my }
        get '/suggested(/:category_id)',  action: :index, as: :suggested, defaults: { scope: :suggested }
        get '/:category_id',              action: :index, as: :category
      end
    end
    resources :profiles, only: [:index] do
      collection do
        get '/:category_id', action: :index, as: :category
      end
    end
  end

  resources :categories, only: [:index]
  resources :deals, only: [:show] do
    resources :comments, only: [:create]
  end

  resources :news, only: [:index, :show]

  resources :help_categories, only: :index, path: 'help', as: :help do
    resources :help_answers, only: :show, path: 'answer', as: :answer
  end
  resources :help_questions, only: [:new, :create], path: 'help'

  resources :vacancies, only: :index

  get '/robots.txt', to: 'main#robots'
  get 'contract_designer/:template_id', to: 'contracts#new', as: :contract_designer

  get '*unmatched_route', to: 'pages#show'
end

app/models/billing/delocoin.rb
class Billing::Delocoin
end

app/models/billing/delocoin/buy.rb
# == Schema Information
#
# Table name: billing_delocoin_buys
#
#  id              :integer          not null, primary key
#  pack_id         :integer
#  pay_type        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  cost            :float
#  delocoin_amount :integer
#  step_id         :integer
#

require_dependency 'billing/delocoin'

class Billing::Delocoin::Buy < ApplicationRecord
  self.table_name = 'billing_delocoin_buys'

  extend Enumerize
  include Billing::Base

  enumerize :pay_type, in: Billing::PaymentTypeList.for(self)

  belongs_to :pack, class_name: '::Delocoin::Pack'
  belongs_to :step, class_name: '::Delocoin::Step'

  def name
    'Покупка DeloСoin'
  end
end

app/models/billing/delocoin/manual_transfer.rb
class Billing::Delocoin::ManualTransfer < ApplicationRecord
  self.table_name = 'billing_delocoin_manual_transfer'

  include Billing::Base

  belongs_to :admin, class_name: 'User'

  validates :admin, presence: true

  def name
    'Ручное пополнение Delocoin'
  end
end

app/models/delocoin/pack.rb
# == Schema Information
#
# Table name: delocoin_packs
#
#  id        :integer          not null, primary key
#  cost      :integer
#  discount  :float
#  number    :integer
#  is_public :boolean          default(FALSE)
#

class Delocoin::Pack < ApplicationRecord
  self.table_name = 'delocoin_packs'

  validates :cost, :discount, presence: true

  scope :is_public, -> { where(is_public: true) }

  after_save do
    Delocoin::Pack::SortService.new.perform
  end
end

app/models/delocoin/step.rb
# == Schema Information
#
# Table name: delocoin_steps
#
#  id            :integer          not null, primary key
#  date_from     :date
#  rate          :float
#  is_current    :boolean
#  number        :integer
#  buy_available :boolean
#

class Delocoin::Step < ApplicationRecord
  self.table_name = 'delocoin_steps'

  validates :date_from, :rate, presence: true

  after_save do
    Delocoin::Step::SortService.new.perform
    Delocoin::Step::SetCurrentService.new.perform
  end
end

app/controllers/delocoins_controller.rb
class DelocoinsController < ApplicationController
  helper_method :last_step, :last_step_delocoin_cost, :current_step_delocoin_cost, :packs

  def new
    run Billing::Delocoin::Buy::Operation::Create::Present
    render 'my/delocoin/buy' if user_signed_in?
  end

  def create
    run Billing::Delocoin::Buy::Operation::Create, delocoin_params do |result|
      sign_in result['sign_in_new_user'] if result['sign_in_new_user']

      payment_model = if result['nested_payment'].present?
                        result['nested_payment']['model']
                      else
                        result['model']
                      end

      roistat.push_async(:delocoin_buy_create, cost: result['model'].cost)
      return redirect_to confirm_my_billing_path(id: payment_model.billing_log.id)
    end

    return render 'my/delocoin/buy' if user_signed_in?
    render 'new'
  end

  private

    def delocoin_params
      params.require(:billing_delocoin_buy).permit!
    end

    def packs
      @packs = if user_signed_in?
                 Delocoin::Pack.order('cost ASC').decorate
               else
                 Delocoin::Pack.is_public.order('cost ASC').decorate
               end
    end

    def last_step
      @last_step = Delocoin::Step::LastService.new.perform
    end

    def last_step_delocoin_cost
      @last_step_delocoin_cost = Delocoin::ConvertService.new.delocoins_to_balance(step: last_step, delocoins: 1)
    end

    def current_step_delocoin_cost
      @current_step_delocoin_cost = Delocoin::ConvertService.new.delocoins_to_balance(step: current_delocoin_step, delocoins: 1)
    end
end

app/controllers/my/delocoin_controller.rb
class My::DelocoinController < My::ApplicationController
  decorates_assigned :packs, :pack

  def index
    @current_delocoin_cost = Delocoin::ConvertService.new.delocoins_to_balance(step: current_delocoin_step, delocoins: 1)

    @steps = Delocoin::Step.order('number ASC').all
  end
end

app/views/delocoins/_new_user_form.html.slim
.registration-form
  .dr-block-style.dr-block-style--sign-in
    h1 Укажите контактную информацию
    .registration-form__content
      .registration-form__content-inputs
        .row
          .col-lg-8
            .form-group
              = f.input :first_name, label: false, error: false
          .col-lg-8
            .form-group
              = f.input :email, label: false, error: false
        br/
        = render 'shared/phone_confirmation', f: f
        .registration-form__content-button-submit
          = f.submit 'Продолжить', class: 'dr-btn-danger'
        br/
        delocoin-omniauth-links(
          :omniauth-params="paramsForOmniauth"
          operation="delocoin"
        )
        br/
        .checkbox.form-group
          label
            = f.hidden_field :accept_terms, value: 1
            span
              ' Нажимая кнопку "Продолжить" или регистрируясь через социальные сети вы соглашаетесь с
              = policy_links true

app/views/delocoins/_payment_methods.html.slim
.dr-content-header
  h2
    | Выберите способ оплаты
delocoin-payment-form(
  value=f.object.pay_type
  :payment-type-list=(Billing::PaymentTypeList.for(model).to_json)
  :cost="cost"
  balance=(user_signed_in? ? current_user.balance : nil)
  @can-pay="canPay = $event"
  @payment-type="paymentType = $event"
)
  template slot="input" scope="props"
    = f.input_field :pay_type, as: :hidden, ':value': 'props.value'

app/views/delocoins/_table_steps.html.slim
.dr-block-style
  h2 Сколько монет Вы хотите приобрести?
  br/
  span.dr-h5 Текущий курс
  .current-rate
    img alt="Delocoin" src="/images/icons/delocoin.svg" /
    span.delocoin-current__value-big 1
    span = '='
    img alt="Ruble" src="/images/icons/ruble.svg" /
    span.delocoin-current__value-big #{number_to_currency(current_step_delocoin_cost, unit: '', precision: 0)}
.dr-block-style.dr-block-style--no-padding
  .delocoin-buy
    h2 Выберите пакет
  delocoin-pack-form(
    last-step-number=last_step.number
    last-step-delocoin-cost=last_step_delocoin_cost
    :packs-list=Entities::Delocoin::Pack.represent(packs).to_json
    v-model="model.pack_id"
    @cost="cost = $event"
    @pack-id="packId = $event"
  )
    template slot="input" scope="props"
      = f.input_field :pack_id, as: :hidden, ':value': 'props.value'

app/views/delocoins/new.html.slim
.regular-content
  .container
    .row.justify-center
      .col-lg-8.col-md-10.col-sm-12
        .dr-content-header
          h1
            | Купить DeloCoin
        delocoin-buy-form(
          inline-template="true"
          :initial-model=@form.to_nested_hash.to_json
        )
          = simple_form_for @form, url: delocoins_path do |f|
            = render 'table_steps', f: f
            = render 'payment_methods', f: f, model: Billing::YandexKassa::Deposit
            = f.simple_fields_for :new_user do |rf|
              - unless rf.object.nil?
                = render 'new_user_form', f: rf