config/routes.rb
Rails.application.routes.draw do
  # Active admin
  ActiveAdmin.routes(self)

  # API
  mount ApplicationAPI => '/api'

  # sidekiq
  require 'sidekiq/web'
  authenticate :user, lambda { |user| user.permission.superadmin? || user.permission.admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  root 'main#index'
  resources :coming_soon_requests, only: [:new, :create], path: '', path_names: {
    new: 'coming-soon',
    create: 'coming-soon'
  } do
    collection do
      post 'main-search', action: :main_search
      get 'coming-soon/thank-you', action: :success, as: :success
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'users/sign_in_as/:type', to: 'users/sessions#sign_in_as', as: :sign_in_as
  end
  resources :users, only: [:index, :destroy]
  resources :delocoins, only: [:new, :create]

  namespace :my do
    resources :welcome, only: :index
    resources :index, only: :index
    resource :user, only: [:edit, :update]
    resource :settings, only: [:edit, :update]
    resources :billing, only: [:index, :create] do
      member do
        get 'confirm', as: :confirm
        post 'confirm'
        get 'status', as: :status
      end
      collection do
        get 'history', as: :history
        resources :yandex_endpoint, path: 'yandex', only: [] do
          get 'success', on: :collection
          match 'fail', via: [:get, :post], on: :collection
        end
      end
    end
    resources :delocoin, only: [:index] do
      collection do
        get 'history', as: :history
      end
    end
    resources :portfolios, except: [:index, :destroy]
  end

  resources :profiles, only: [:show, :edit, :update], path: 'profile'
  resources :profiles, only: [:new, :create]

  resources :tasks, only: [:show, :edit, :update, :destroy], path: 'task' do
    resources :replies, only: [:show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create]
      member do
        get 'cancel_decline'
        get 'decline'
        get 'accept'
        get 'delete'
      end
    end
  end
  resources :tasks, only: [:new, :create], path_names: { new: 'new(/:category_id)' }

  scope '(/:city_code)' do
    resources :tasks, only: [:index] do
      collection do
        get '/my(/:category_id)',         action: :index, as: :my,        defaults: { scope: :my }
        get '/suggested(/:category_id)',  action: :index, as: :suggested, defaults: { scope: :suggested }
        get '/:category_id',              action: :index, as: :category
      end
    end
    resources :profiles, only: [:index] do
      collection do
        get '/:category_id', action: :index, as: :category
      end
    end
  end

  resources :categories, only: [:index]
  resources :deals, only: [:show] do
    resources :comments, only: [:create]
  end

  resources :news, only: [:index, :show]

  resources :help_categories, only: :index, path: 'help', as: :help do
    resources :help_answers, only: :show, path: 'answer', as: :answer
  end
  resources :help_questions, only: [:new, :create], path: 'help'

  resources :vacancies, only: :index

  get '/robots.txt', to: 'main#robots'
  get 'contract_designer/:template_id', to: 'contracts#new', as: :contract_designer

  get '*unmatched_route', to: 'pages#show'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id             :integer          not null, primary key
#  title          :string
#  parent_id      :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  lft            :integer
#  rgt            :integer
#  depth          :integer
#  children_count :integer
#  photo          :string
#  position       :integer
#  slug           :string
#  settings       :text
#  description    :text
#  is_main        :boolean          default(FALSE)
#
# Indexes
#
#  index_categories_on_slug  (slug) UNIQUE
#

class Category < ApplicationRecord
  include FriendlyId
  include Searchable::Category

  serialize :settings, OpenStruct

  mount_uploader :photo, CategoryPhotoUploader
  acts_as_nested_set counter_cache: :children_count
  acts_as_list scope: [:parent_id], top_of_list: 0

  validates :title, :slug, presence: true, length: { maximum: 250 }
  validates :slug, uniqueness: true
  validates :position, numericality: { only_integer: true }, allow_blank: true

  friendly_id :title, use: :slugged

  belongs_to :parent, class_name: 'Category'
  has_many :tasks

  has_and_belongs_to_many :profiles

  scope :main, -> { where(is_main: true) }

  def self_and_descendants_ids
    self_and_descendants.map(&:id)
  end
end

app/models/concerns/searchable/category.rb
module Searchable::Category
  extend ActiveSupport::Concern

  included do
    searchkick word_start: [:title], language: :russian

    scope :by_search_in, ->(q) {
      search_by_ids CategorySearch.new(query: q, page: 1, per_page: 100).all.map(&:id)
    }

    scope :by_search_in_tasks, ->(q) {
      search_by_ids TaskCategoriesSearch.new(query: q, page: 1, per_page: 100).categories_ids
    }

    def self.ransackable_scopes auth_object = nil
      [:by_search_in]
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Pundit

  def index
    @categories = Category.roots.includes(:children).except(:order).order(:position)
  end
end

app/views/categories/_breadcrumb.html.slim
nav.breadcrumb
  a.breadcrumb-item href=root_path  Главная
  span.breadcrumb-item.active Все категории услуг
.dr-content-header
  h1
    | Какой вид работы вас интересует?

app/views/categories/_description.html.slim
- description = parse_seo_settings(@place_settings, :description)
- if @category and description.present?
  .dr-block-style
    hide-show-element(
      inline-template="true"
    )
      .bottom-text.center
        span.all_text(v-show="isShow")
          = simple_format description.html_safe
        span.short_text(v-show="!isShow")
          = simple_format description.truncate(150).html_safe
          - if description.length > 150
            a.link-default.category_desc_accordion href="#" @click.prevent="toggleShow" Развернуть

app/views/categories/index.html.slim
.regular-content
  .container
    = render 'breadcrumb'
    - @categories.each_slice(3).to_a.each_with_index do |category_array, index|
      = content_tag(:div, '', class: 'spacer-lg') if index > 0
      .row.align-items-stretch
        - category_array.each do |category|
          .col-lg-4
            .dr-block-style.dr-block-style--card-category
              .category-card
                .category-card__header
                  = image_tag category.photo.url(:thumb)
                  h3= link_to category.title, new_task_path(category)
                .category-card__content
                  ul.category-card__list
                    - if category.children.blank?
                      | Список подкатегорий пуст
                    - else
                      - category.children.each do |child|
                        li
                          = link_to child.title, new_task_path(child)